import Footer from "@/components/admin/Footer";
import Sidebar from "@/components/admin/Sidebar";

export const metadata = {
	title: "EcommerCe | Admin",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<div className=" lg:flex">
			<Sidebar />
			<div className="flex flex-auto flex-col lg:min-h-screen px-8 py-4">
				<div className="flex flex-auto bg-amber-200">{children}</div>
				<div className="divider "></div>
				<Footer />
			</div>
		</div>
	);
}
